package com.dev.delta.dto;

import com.dev.delta.entities.AdvanceSalary;
import com.dev.delta.entities.Announcement;
import com.dev.delta.entities.Award;
import com.dev.delta.entities.City;
import com.dev.delta.entities.Complain;
import com.dev.delta.entities.Contract;
import com.dev.delta.entities.ContractType;
import com.dev.delta.entities.Country;
import com.dev.delta.entities.Departement;
import com.dev.delta.entities.EducationLevel;
import com.dev.delta.entities.Employee;
import com.dev.delta.entities.Event;
import com.dev.delta.entities.Holiday;
import com.dev.delta.entities.Job;
import com.dev.delta.entities.JobApplication;
import com.dev.delta.entities.Leave;
import com.dev.delta.entities.Loan;
import com.dev.delta.entities.Location;
import com.dev.delta.entities.Meeting;
import com.dev.delta.entities.Notice;
import com.dev.delta.entities.Position;
import com.dev.delta.entities.Resignation;
import com.dev.delta.entities.Salary;
import com.dev.delta.entities.Termination;
import com.dev.delta.entities.Trainer;
import com.dev.delta.entities.Training;
import com.dev.delta.entities.Transfer;
import com.dev.delta.entities.TypeAward;
import com.dev.delta.entities.TypeLeave;
import com.dev.delta.entities.TypeTermination;
import com.dev.delta.entities.TypeTraining;
import com.dev.delta.entities.User;
import com.dev.delta.entities.Warning;

public interface DTO {

	AdvanceSalary advanceSalary=new AdvanceSalary() ;
	Announcement announcement=new Announcement() ;
	Award award=new Award();
	City city=new City();
	Complain complain=new Complain();
	Contract contract=new Contract();
	ContractType contractType=new ContractType();
	Country country=new Country();
	Departement departement=new Departement();
	EducationLevel educationLevel=new EducationLevel();
	Employee employee=new Employee();
	Event event=new Event();
	Holiday holiday=new Holiday();
	Job job=new Job();
	JobApplication jobApplication=new JobApplication();
	Leave leave=new Leave();
	Loan loan=new Loan();;
	Location location=new Location();
	Meeting meeting=new Meeting();
	Notice notice=new Notice();
	Position position=new Position() ;
	Resignation resignation=new Resignation();
	Salary salary=new Salary();
	Termination termination=new Termination();
	Trainer trainer=new Trainer();
	Training training=new Training();
	Transfer transfer=new Transfer();
	TypeAward typeAward=new TypeAward();
	TypeLeave typeLeave=new TypeLeave();
	TypeTermination termination2=new TypeTermination();
	TypeTraining training2=new TypeTraining();
	User user=new User();
	Warning warning=new Warning();
	public void populate();
}
